[supervisord]
nodaemon=true

[program:twincat]
command=/usr/bin/sh /app/tcstart.sh
priority=10
autostart=true
autorestart=true

[program:python]
directory=/app
command=uv run python main.py
priority=20
autostart=true
autorestart=true
